### ISSUE TITLE
No module named 'HRNET.yolov6.YOLOv6'

### ISSUE THREAD

**Issue by MArbane** [ibaiGorordo/ONNX-HRNET-Human-Pose-Estimation#1]
hello, 
Please, I faced this problem when I was trying to execute the code! 
I didn't find this file. Can you help me with it? 

![issue](https://user-images.githubusercontent.com/107846369/177175610-5a908874-3d41-45c6-9644-1fda1198bf02.png)

**Comment by MArbane** [comment]
I fixed this problem , but i faced this one now any suggestions? 
![image](https://user-images.githubusercontent.com/107846369/177179466-bef5e756-798b-49bf-90cd-9fe45c283af5.png)

**Comment by ibaiGorordo** [comment]
Follow the instructions in the [Readme](https://github.com/ibaiGorordo/ONNX-HRNET-Human-Pose-Estimation/blob/main/README.md).

For other people with the same issue:
- For the first issue, you also need to clone the yolov6 submodule (not just clone):
`git clone https://github.com/ibaiGorordo/ONNX-HRNET-Human-Pose-Estimation.git --recursive`
- For the missing model files, you need to download them as explained in the [Readme - ONNX models](https://github.com/ibaiGorordo/ONNX-HRNET-Human-Pose-Estimation/blob/main/README.md#onnx-runtime), at least the HRNET or LiteHRNET models for the single pose examples, and additionally YOLOv6 or YOLOv5 for the multi pose examples.
